version: '3'

services:
  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - my-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - my-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - my-network
    depends_on:
      - eureka
      - zipkin
    links:
      - eureka
      - zipkin

  one-business:
    build:
      context: ./one-business
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - eureka
      - zipkin
    links:
      - eureka
      - zipkin

  two-business:
    build:
      context: ./two-business
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - my-network
    depends_on:
      - eureka
      - zipkin
      - one-business
    links:
      - eureka
      - zipkin
      - one-business

  consul:
    image: consul
    ports:
      - "8500:8500"
    networks:
      - my-network

  archaius:
    build:
      context: ./archaius
      dockerfile: Dockerfile
    depends_on:
      - consul
    links:
      - consul
    ports:
      - "8089:8089"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge