server:
  port: 8089

spring:
  application:
    name: archaius-fake
  config:
    import: 'optional:consul:'
  cloud:
    consul:
      host: http://consul
      port: 8500
      config:
        format: yaml
        enabled: true